name: Standard Pipeline

on:
  push:
  pull_request:

jobs:
  outdated:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: 4.0.0

    - name: build
      run: R CMD build . --no-build-vignettes --no-manual

    - name: check
      run: R CMD check *tar.gz --no-build-vignettes --no-manual

  docker:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: docker build
      run: docker build -t r-demo .