name: Standard Pipeline

on:
  push:
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: docker build
      run: docker build -t r-demo -f Dockerfile .